version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test-template -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e-demo -- --protractor-config=projects/demo/e2e/protractor-ci.conf.js
