version: 2.1
jobs:
  test-demo:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: E2E tests for demo app
          command: npm run e2e-demo -- --protractor-config=projects/demo/e2e/protractor-ci.conf.js
  test-template:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: 
          name: Test ng-template
          command: npm run test-template -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  publish-template:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          key: template-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: 
          name: Build ng-template
          command: npm run build-template
      - run:
          name: Publish to NPM
          command: | 
            cd ./dist/template
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  test-publish-template:
    jobs:
      - test-template
      - publish-template:
          requires:
            - test-template
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d)+(\.(\d)+)+$/
  test-demo:
    jobs:
      - test-demo